[tool.poetry]
name = "gpt-wordpress-plugin-generator"
package-mode = false


[tool.poetry.dependencies]
python = "^3.12"
click = "^8.1.7"
openai = "^1.40.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
